# Generated by Django 5.1.3 on 2024-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
